/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.AccesoProveedor;
import Entidades.Proveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class RegistroProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroProveedor
     */
    public RegistroProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textDomicilio = new javax.swing.JTextField();
        GUARDAR = new javax.swing.JButton();
        BUSCAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("REGISTRO DE PROVEEDORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 460, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Razon Social");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Domicilio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));
        getContentPane().add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 105, -1));

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        getContentPane().add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 239, 337, -1));
        getContentPane().add(textDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 305, 337, -1));

        GUARDAR.setBackground(new java.awt.Color(102, 102, 102));
        GUARDAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GUARDAR.setForeground(new java.awt.Color(255, 255, 255));
        GUARDAR.setText("GUARDAR");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 443, 119, 47));

        BUSCAR.setBackground(new java.awt.Color(102, 102, 102));
        BUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });
        getContentPane().add(BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 111, 53));

        MODIFICAR.setBackground(new java.awt.Color(102, 102, 102));
        MODIFICAR.setForeground(new java.awt.Color(255, 255, 255));
        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 443, 114, 47));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Numero de contacto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 375, -1, -1));

        textNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 372, 337, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ELIMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 111, 51));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 443, 132, 47));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 710, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        // TODO add your handling code here:
        AccesoProveedor prod = new AccesoProveedor();
        String idProveedor = textId.getText();
        if(!contieneLetras(idProveedor)){
        Proveedor p = prod.buscarProveedor(Integer.parseInt(idProveedor));
        textNombre.setText(p.getRazonSocial());
        textDomicilio.setText(p.getDireccion());
        textNumero.setText(""+p.getTelefono());
        } else {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese valores válidos en el CAMPO ID.");
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
        AccesoProveedor acc = new AccesoProveedor();
        Proveedor pr = new Proveedor();
        String nombre = textNombre.getText();
        String domicilio = textDomicilio.getText();
        String num = textNumero.getText();
        
        if (!contieneNumeros(nombre)&& !contieneLetras(num)){
        
        pr.setRazonSocial(textNombre.getText());
        pr.setDireccion(textDomicilio.getText());
        pr.setTelefono(Integer.parseInt(textNumero.getText()));
        
        acc.guardarProveedor(pr);
        Limpiar();
        
        }else{
        
            JOptionPane.showMessageDialog(null, "Por favor, ingrese valores válidos en los campos.");
        if (contieneNumeros(nombre)){
            textNombre.setText("");
        }

        if (contieneLetras(num)){
            textNumero.setText("");
        }
        
        }
        
        
        
    }//GEN-LAST:event_GUARDARActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
        AccesoProveedor c = new AccesoProveedor();
        Proveedor pr = new Proveedor();
        
        String nombre = textNombre.getText();
        String domicilio = textDomicilio.getText();
        String num = textNumero.getText();
        
        
        if (!contieneNumeros(nombre)&& !contieneLetras(num)){
        pr.setRazonSocial(textNombre.getText());
        pr.setDireccion(textDomicilio.getText());
        pr.setTelefono(Integer.parseInt(textNumero.getText()));
        pr.setId(Integer.parseInt(textId.getText()));

        c.modificarProveedor(pr);
        }else{
        
            JOptionPane.showMessageDialog(null, "Por favor, ingrese valores válidos en los campos.");
        if (contieneNumeros(nombre)){
            textNombre.setText("");
        }

        if (contieneLetras(num)){
            textNumero.setText("");
        }
        
        }
        
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AccesoProveedor acc = new AccesoProveedor();
        String idProveedor = textId.getText();
        if(!contieneLetras(idProveedor)){
        acc.eliminarProveedor(Integer.parseInt(textId.getText()));
        } else {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese valores válidos en el CAMPO ID.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textDomicilio;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNumero;
    // End of variables declaration//GEN-END:variables

    
    public void Limpiar(){
        
        textId.setText("");
        textNombre.setText("");
        textDomicilio.setText("");
        textNumero.setText("");


    }
    
      private boolean contieneNumeros(String texto) {
    for (char c : texto.toCharArray()) {
        if (Character.isDigit(c)) {
            return true;
        }
    }
    return false;
}

    private boolean contieneLetras(String texto) {
    for (char c : texto.toCharArray()) {
        if (Character.isLetter(c)) {
            return true;
        }
    }
    return false;
}

}
